export default {
    items: [{
            id: "accueil",
            title: "Accueil",
            type: "item",
            position: "nav",
            url: "/accueil",
            icon: "feather icon-home",
        },
        {
            id: "blog",
            title: "blog",
            type: "item",
            position: "nav",
            url: "/blog",
            icon: "feather icon-edit",
        },
        {
            id: "contacts",
            title: "Contacts",
            type: "item",
            position: "nav",
            url: "/contacts",
            icon: "feather icon-file-text",
        },
        {
            id: "a-propos",
            title: "A Propos",
            type: "item",
            position: "nav",
            url: "/a-propos",
            icon: "feather icon-download",
        },
    ],
};